rakusuke/config/routes.rb
Rails.application.routes.draw do

  devise_for :people, only: [:sign_in, :sign_out, :session, :password]
  resources :people
  devise_for :admins

  resources :transfer_destinations

  resources :children

  resources :schedules do
    member do
      patch 'edit_transfer_dests'
    end
  end

  post 'schedules/kakutei/:ids' => 'schedules#kakutei'

  root :to => 'home#index'

end

rakusuke/app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: [:show, :edit, :update, :destroy]

  # GET /children
  # GET /children.json
  def index
    # @children = Child.all
    p "params[:person_id]"
    p params[:person_id]
    @children = Person.find(params[:person_id]).children

  end

  # GET /children/1
  # GET /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new
    @child.person_id = params[:person_id].to_i
  end

  # GET /children/1/edit
  def edit
  end

  # POST /children
  # POST /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        # format.html { redirect_to @child, notice: 'Child was successfully created.' }
        format.html { redirect_to person_url(:id => @child.person_id),
                                  notice: '登録されました。' }

        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1
  # PATCH/PUT /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to @child, notice: '更新されました。' }
        format.json { render :show, status: :ok, location: @child }
      else
        format.html { render :edit }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1
  # DELETE /children/1.json
  def destroy
    @child.destroy
    respond_to do |format|
      format.html { redirect_to person_url(:id => @child.person_id),
                                notice: '削除されました。' }

      # format.html { redirect_to children_url, notice: 'Child was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def child_params
      params.require(:child).permit(:person_id, :first_name, :last_name, :memo, :deleted_at)
    end
end

rakusuke/app/helpers/children_helper.rb
module ChildrenHelper
end

rakusuke/app/views/children/_form.html.erb
<%= form_for(@child) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
      <% @child.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :person_id, :value => @child.person_id %>
  <div class="field">
    <%= f.label :姓 %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :名 %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :メモ %><br>
    <%= f.text_area :memo %>
  </div>
  <!--<div class="field">-->
    <!--<%= f.label :deleted_at %><br>-->
    <!--<%= f.datetime_select :deleted_at %>-->
  <!--</div>-->
  <div class="actions">
    <%= f.submit '送信' %>
  </div>
<% end %>

rakusuke/app/views/children/edit.html.erb
<div data-role="header">
  <%= link_to '戻る',person_path(id: @child.person_id), "data-icon"=>"arrow-l" %>
  <%= link_to '詳細', @child, "data-icon"=>"arrow-R" %> |
  <h1>子供編集</h1>
</div>

<%= render 'form' %>

rakusuke/app/views/children/index.html.erb
<h1>子供</h1>

<table class="tablesorter">
  <thead>
    <tr>
      <th>姓</th>
      <th>名</th>
      <th>メモ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @children.each do |child| %>
      <tr>
        <td><%= child.last_name %></td>
        <td><%= child.first_name %></td>
        <td><%= child.memo %></td>
        <td><%= link_to '詳細', child %></td>
        <td><%= link_to '編集', edit_child_path(child) %></td>
        <td><%= link_to '削除', child, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

rakusuke/app/views/children/new.html.erb
<div data-role="header">
  <%= link_to '戻る',person_path(id: @child.person_id), "data-icon"=>"arrow-l" %>
  <h1>子供登録</h1>
</div>

<%= render 'form' %>

rakusuke/app/views/children/show.html.erb
<script src="http://code.jquery.com/jquery-1.8.3.js"></script>
<script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>

<div data-role="header">
  <%= link_to '戻る',person_path(id: @child.person_id), "data-icon"=>"arrow-l" %>
  <%= link_to '編集', edit_child_path(@child), "data-icon"=>"arrow-l" %>
  <h1>子供詳細</h1>
</div>



<p id="notice"><%= notice %></p>
<p>
  <strong>姓:</strong>
  <%= @child.last_name %>
</p>
<p>
  <strong>名:</strong>
  <%= @child.first_name %>
</p>
<p>
  <strong>メモ:</strong>
  <%= @child.memo %>
</p>

<div id="show_area"></div>

<%= link_to '新規作成', new_transfer_destination_path(:child_id => @child.id) %>


<script type = "text/javascript">

    $(document).ready(function(){
        $.get("<%= transfer_destinations_path :child_id => @child.id %>",
                function(data) { $('#show_area').html(data) } )

        $('a.index').click(function() {
            $.get("<%= transfer_destinations_path :chiild_id => @child.id %>",
                    function(data) { $('#show_area').html(data) } )
        })

    })
</script>