rakusuke/config/routes.rb
Rails.application.routes.draw do

  devise_for :people, only: [:sign_in, :sign_out, :session, :password]
  resources :people
  devise_for :admins

  resources :transfer_destinations

  resources :children

  resources :schedules do
    member do
      patch 'edit_transfer_dests'
    end
  end

  post 'schedules/kakutei/:ids' => 'schedules#kakutei'

  root :to => 'home#index'

end

rakusuke/app/models/schedule.rb
class Schedule < ActiveRecord::Base

  belongs_to :person
  belongs_to :child
  belongs_to :transfer_destination

  # 送迎区分
  PICKUP_DIVS = [['送り', '01'], ['迎え', '02']]

  # ステータス区分
  STATUS_DIVS_FOR_MASTER = [['希望', '01'], ['確定', '02'], ['キャンセル', '03'], ['仮登録', '04']]
  STATUS_DIVS_FOR_PERSON = [['希望', '01'], ['キャンセル', '03']]

  # 利用時間帯(休日)
  USE_TIME_HOLIDAY_DIVS = [['10:00〜12:00', '04'],
                           ['14:00〜16:00', '05'],
                           ['10:00〜16:00', '06']]

  # 利用時間帯(平日)
  USE_TIME_WEEKDAY_DIVS = [['14:00〜16:30', '01'],
                           ['17:30〜18:30', '02'],
                           ['14:00〜18:30', '03']]

  def status_name
    unless self.status_div.blank?
      STATUS_DIVS_FOR_MASTER.rassoc(self.status_div)[0]
    end
  end

  def pickup_name
    unless self.pickup_div.blank?
      PICKUP_DIVS.rassoc(self.pickup_div)[0]
    end
  end

  def use_time_name
    use_time_divs = Schedule::USE_TIME_HOLIDAY_DIVS
    use_time_divs.concat(Schedule::USE_TIME_WEEKDAY_DIVS)
    unless self.use_time_div.blank?
      use_time_divs.rassoc(self.use_time_div)[0]
    end
  end

  def estimated_time_of_arrival_
    unless self.estimated_time_of_arrival.blank?
      self.estimated_time_of_arrival
    else
      " - "
    end
  end

  def get_out_of_school_time_
    unless self.get_out_of_school_time.blank?
      self.get_out_of_school_time
    else
      " - "
    end
  end

  def desired_time_
    unless self.desired_time.blank?
      self.desired_time
    else
      " - "
    end
  end

  def child_list_for_admin

    child_list = Child.limit(50).order("updated_at DESC")

    child_list_array = []

    child_list.each do |child|
      child_list_array.push([child.full_name, child.id])
    end

    child_list_array
  end

  def child_list_for_person(person)
    child_list = person.children.limit(50).order("updated_at DESC")

    child_list_array = []

    child_list.each do |child|
      child_list_array.push([child.full_name, child.id])
    end

    child_list_array
  end


  def transfer_destination_list_for_child
    transfer_destinations = self.child.transfer_destinations.limit(50).order("updated_at DESC")

    transfer_destination_list = []

    transfer_destinations.each do |transfer_destination|
      transfer_destination_list.push([transfer_destination.name, transfer_destination.id])
    end

    transfer_destination_list

  end

end

rakusuke/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy, :edit_transfer_dests]

  # GET /schedules
  # GET /schedules.json
  def index
    if current_person.is_a?(Admin)
      @schedules = Schedule.order("updated_at DESC")
    elsif current_person.is_a?(Person)
      @schedules = current_person.schedules.order("updated_at DESC")
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /edit_transfer_dests
  # POST /edit_transfer_dests.json
  def edit_transfer_dests
    parsed_params = params_for_action_create(schedule_params)
    logger.debug("edit_transfer_dests")
    logger.debug("schedule_params=#{schedule_params}")
    logger.debug("parsed_params=#{parsed_params}")
    logger.debug("@schedule_before=#{@schedule.inspect}")
    # @schedule = Schedule.new(parsed_params)
    @schedule.update(parsed_params)
    logger.debug("@schedule_after=#{@schedule.inspect}")
    @schedule
  end

  # POST /schedules
  # POST /schedules.json
  def create
    parsed_params = params_for_action_create(schedule_params)

    @schedule = Schedule.new(parsed_params)
    logger.debug("schedule_params=#{schedule_params}")
    logger.debug("@schedule=#{@schedule}")
    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: '登録されました。' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      parsed_params = params_for_action_create(schedule_params)

      if params[:id] == '0'
        @schedule = Schedule.new(parsed_params)
        if @schedule.save
          format.html { redirect_to @schedule, notice: '登録されました。' }
          format.json { render :show, status: :created, location: @schedule }
        else
          format.html { render :new }
          format.json { render json: @schedule.errors, status: :unprocessable_entity }
        end

      else
        if @schedule.update(parsed_params)
          format.html { redirect_to @schedule, notice: '更新されました。' }
          format.json { render :show, status: :ok, location: @schedule }
        else
          format.html { render :edit }
          format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: '削除されました。' }
      format.json { head :no_content }
    end
  end

  def kakutei
    ids = params[:ids].split(",")
    logger.debug("ids= #{ids.inspect}")
    ids.each do |id|
      @schedule = Schedule.find(id)
      @schedule.status_div = '02'
      @schedule.save
    end
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      if params[:id] == '0'
        @schedule = Schedule.new
      else
        @schedule = Schedule.find(params[:id])
      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:id, :person_id, :date, :pickup_div, :transfer_destination_id, :estimated_time_of_arrival, :child_id, :use_time_div, :get_out_of_school_time, :desired_time, :status_div, :memo, :deleted_at)
    end

    def params_for_action_create(params={})
      # 親のidをセット
      child = Child.find(params[:child_id])
      person = child.person
      params[:person_id] = person.id
      parsed_params = params.dup
      logger.debug("parsed_params=#{parsed_params}")
      return parsed_params
    end

  def params_for_action_update(params={})
    parsed_params = params.dup
    logger.debug("parsed_params=#{parsed_params}")
    return parsed_params
  end
end

rakusuke/app/helpers/schedules_helper.rb
module SchedulesHelper
end

rakusuke/app/views/schedules/_form.html.erb
<%= form_for :schedule, url: edit_transfer_dests_schedule_path(id:(@schedule.id.blank?) ? 0: @schedule.id), method: :patch do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% @schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div data-role="fieldcontain">
    <%= f.label :予定日 %><br>
    <%= f.text_field :date, id:'datepicker' %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :送迎区分 %><br>
    <%= f.select(:pickup_div, options_for_select(Schedule::PICKUP_DIVS, @schedule[:pickup_div])) %>
  </div>
  <% if (current_person.is_a?(Admin)) %>
    <div data-role="fieldcontain">
      <%= f.label :到着予定時刻 %><br>
      <%= f.text_field :estimated_time_of_arrival, :type=>"text", :id=>"datetimepicker1" %>
    </div>
  <% end %>
  <div data-role="fieldcontain">
    <%= f.label :氏名 %><br>
    <% if (current_person.is_a?(Admin)) %>
      <%= f.select(:child_id, options_for_select(@schedule.child_list_for_admin, @schedule[:child_id])) %>
    <% elsif (current_person.is_a?(Person)) %>
        <%= f.select(:child_id, options_for_select(@schedule.child_list_for_person(current_person), @schedule[:child_id])) %>
    <% end %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :利用時間帯 %><br>
    <% if [5, 6].include?(Time.now.wday-1) || !(Time.now.extend Shukujitu).shukujitu?.blank? %>
      <%= f.select(:use_time_div, options_for_select(Schedule::USE_TIME_HOLIDAY_DIVS, @schedule[:use_time_div])) %>
    <% else %>
      <%= f.select(:use_time_div, options_for_select(Schedule::USE_TIME_WEEKDAY_DIVS, @schedule[:use_time_div])) %>
    <% end %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :下校時刻 %><br>
    <%= f.text_field :get_out_of_school_time, :type=>"text", :id=>"datetimepicker2" %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :希望時刻 %><br>
    <%= f.text_field :desired_time, :type=>"text", :id=>"datetimepicker3" %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :ステータス %><br>
    <% if (current_person.is_a?(Admin)) %>
      <%= f.select(:status_div, options_for_select(Schedule::STATUS_DIVS_FOR_MASTER, @schedule[:status_div])) %>
    <% elsif (current_person.is_a?(Person)) %>
      <%= f.select(:status_div, options_for_select(Schedule::STATUS_DIVS_FOR_PERSON, @schedule[:status_div])) %>
    <% end %>


  </div>
  <div data-role="fieldcontain">
    <%= f.label :備考 %><br>
    <%= f.text_area :memo %>
  </div>
  <div data-role="fieldcontain">
    <%= f.submit '次へ' %>
  </div>
<% end %>

<script>
  $('#datetimepicker1').datetimepicker({
    datepicker:false,
    format:'H:i',
    step:5
  });
  $('#datetimepicker2').datetimepicker({
    datepicker:false,
    format:'H:i',
    step:5
  });
  $('#datetimepicker3').datetimepicker({
    datepicker:false,
    format:'H:i',
    step:5
  });


</script>

rakusuke/app/views/schedules/_form_smart_phone_iphone.html.erb
<%= form_for :schedule, url: edit_transfer_dests_schedule_path(id:(@schedule.id.blank?) ? 0: @schedule.id), method: :patch do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div data-role="fieldcontain">
  <%= f.label :予定日 %><br>
    <%= f.text_field :date, "type"=>"date", "data-role" => "datebox","data-options" => '{"mode": "calbox"}' %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :送迎区分 %><br>
    <%= f.select(:pickup_div, options_for_select(Schedule::PICKUP_DIVS, @schedule[:pickup_div])) %>
  </div>
  <% if (current_person.is_a?(Admin)) %>
  <div data-role="fieldcontain">
    <%= f.label :到着予定時刻 %><br>
    <%= f.text_field :estimated_time_of_arrival, "type"=>"text", "data-role" => "datebox","data-options" => '{"mode": "timebox", "useNewStyle":true}' %>
  </div>
  <% end %>
  <div data-role="fieldcontain">
    <%= f.label :氏名 %><br>
    <% if (current_person.is_a?(Admin)) %>
      <%= f.select(:child_id, options_for_select(@schedule.child_list_for_admin, @schedule[:child_id])) %>
    <% elsif (current_person.is_a?(Person)) %>
      <%= f.select(:child_id, options_for_select(@schedule.child_list_for_person(current_person), @schedule[:child_id])) %>
    <% end %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :利用時間帯 %><br>
    <% if [5, 6].include?(Time.now.wday-1) || !(Time.now.extend Shukujitu).shukujitu?.blank? %>
      <%= f.select(:use_time_div, options_for_select(Schedule::USE_TIME_HOLIDAY_DIVS, @schedule[:use_time_div])) %>
    <% else %>
      <%= f.select(:use_time_div, options_for_select(Schedule::USE_TIME_WEEKDAY_DIVS, @schedule[:use_time_div])) %>
    <% end %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :下校時刻 %><br>
    <%= f.text_field :get_out_of_school_time, "type"=>"text", "data-role" => "datebox","data-options" => '{"mode": "timebox", "useNewStyle":true}' %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :希望時刻 %><br>
    <%= f.text_field :desired_time, "type"=>"text", "data-role" => "datebox","data-options" => '{"mode": "timebox", "useNewStyle":true}' %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :ステータス %><br>
    <% if (current_person.is_a?(Admin)) %>
      <%= f.select(:status_div, options_for_select(Schedule::STATUS_DIVS_FOR_MASTER, @schedule[:status_div])) %>
    <% elsif (current_person.is_a?(Person)) %>
      <%= f.select(:status_div, options_for_select(Schedule::STATUS_DIVS_FOR_PERSON, @schedule[:status_div])) %>
    <% end %>
  </div>
  <div data-role="fieldcontain">
    <%= f.label :備考 %><br>
    <%= f.text_area :memo %>
  </div>
  <div data-role="fieldcontain">
    <%= f.submit '送信' %>
  </div>
<% end %>

rakusuke/app/views/schedules/edit.html.erb
<div data-role="header">
  <%= link_to '戻る', schedules_path, "data-icon"=>"arrow-l" %> |
  <%= link_to '詳細', @schedule, "data-icon"=>"arrow-R" %>
  <h1>スケジュール編集</h1>
</div>

<%= render 'form' %>

rakusuke/app/views/schedules/edit_transfer_dests.html.erb
<div data-role="header">
  <%= link_to '戻る', edit_schedule_path(@schedule), "data-icon"=>"arrow-l" %>
  <h1>送迎先編集</h1>
</div>


<%= form_for :schedule, url: schedule_path(@schedule), method: :patch, id:(@schedule.id.blank?) ? 0: @schedule.id  do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% @schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div data-role="fieldcontain" class="hide">
    <%= f.label :送迎先 %><br>
    <%= f.select(:transfer_destination_id, options_for_select(@schedule.transfer_destination_list_for_child, @schedule[:transfer_destination_id]), name:"select1") %>
  </div>

  <%= f.hidden_field :id, :value => @schedule.id %>
  <%= f.hidden_field :date, :value => @schedule.date %>
  <%= f.hidden_field :pickup_div, :value => @schedule.pickup_div %>
  <%= f.hidden_field :estimated_time_of_arrival, :value => @schedule.estimated_time_of_arrival_ %>
  <%= f.hidden_field :child_id, :value => @schedule.child_id %>
  <%= f.hidden_field :use_time_div, :value => @schedule.use_time_div %>
  <%= f.hidden_field :get_out_of_school_time, :value => @schedule.get_out_of_school_time_ %>
  <%= f.hidden_field :desired_time, :value => @schedule.desired_time_ %>
  <%= f.hidden_field :status_div, :value => @schedule.status_div %>
  <%= f.hidden_field :memo, :value => @schedule.memo %>

  <div data-role="fieldcontain">
    <%= f.submit '送信' %>
  </div>
<% end %>

rakusuke/app/views/schedules/index.html.erb
<h1>予定表</h1>

<%= link_to '新規', new_schedule_path %>
<% if (current_person.is_a?(Admin)) %>
  <button type="button" name="kakutei">確定</button>
<% end %>

<table id="scheduleTable" class="tablesorter">
  <thead>
    <tr>
      <th><input type="checkbox" class="js-checkAllInTable"></th>
      <th>予定日</th>
      <th>送迎区分</th>
      <th>到着予定時刻</th>
      <th>氏名</th>
      <th>利用時間帯</th>
      <th>下校時刻</th>
      <th>希望時刻</th>
      <th>ステータス</th>
      <th>備考</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><input type="checkbox" id="check" value="<%= schedule.id %>"></td>
        <td><%= schedule.date %></td>
        <td><%= schedule.pickup_name %></td>
        <td><%= schedule.estimated_time_of_arrival_ %></td>
        <td><%= schedule.child.full_name unless schedule.child.blank? %></td>
        <td><%= schedule.use_time_name %></td>
        <td><%= schedule.get_out_of_school_time_ %></td>
        <td><%= schedule.desired_time_ %></td>
        <td><%= schedule.status_name %></td>
        <td><%= schedule.memo %></td>
        <td><%= link_to '詳細', schedule %></td>
        <td><%= link_to '編集', edit_schedule_path(schedule) %></td>
        <td><%= link_to '削除', schedule, method: :delete, data: { confirm: '本当に削除をしますか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div id="pager" class="pager">
  <form>
    <button class="first"><<</button>
    <button class="prev"><</button>
    <input type="text" class="pagedisplay"/>
    <button class="next">></button>
    <button class="last">>></button>
    <select class="pagesize">
      <option value="10">10</option>
      <option value="20">20</option>
      <option value="30">30</option>
      <option value="40">40</option>
      <option selected="selected" value="50">50</option>
      <option value="100">100</option>
    </select>
  </form>
</div>

<script type="text/javascript">

  // ソートとページング
  $(document).ready(function(){
            $("#scheduleTable").tablesorter({
              headers: {
                0: { sorter: false } , 10: { sorter: false }   // 1列目のソートを無効にする
              }
            })
            .tablesorterPager({container: $("#pager")});
  });

  // 確定ボタン押下時の処理
  $(document).on("click", "[name='kakutei']", function(e) {
    var arr = new Array();
    $('[id="check"]:checked').each(function(){
      arr.push($(this).val());
    });
    console.log("選択したID");
    console.log(arr);
    if (arr.length == 0) {
      alert("スケジュールを選択してから押してください。");
    } else {
      $.post('/schedules/kakutei/'+ arr);
    }
  });

  //見出し行のチェックボックスに class="js-checkAllInTable" などのクラス名を付けておくとする
  $(function() {
    //一覧での全チェック
    $('.js-checkAllInTable').on('click', function(){
      $(this).parents('table:eq(0)').find('input[type="checkbox"]').prop('checked', this.checked);
    });
  });
</script>

rakusuke/app/views/schedules/index_smart_phone_iphone.html.erb
<div>
  <div data-role="header">
    <h1>スケジュール</h1>
    <%= link_to '新規', new_schedule_path, "data-icon" => "plus", "class" => "ui-btn-right" %>
  </div>

  <div data-role="content">
    <ul data-role="listview">
      <% @schedules.each do |schedule| %>
        <li data-role="list-divider" style="padding: 0.1em 15px;"><%= schedule.date %></li>
        <li><%= link_to schedule.pickup_name + " 予定 " + schedule.estimated_time_of_arrival_ + " 時 " ,
                        schedule %></li>
      <% end %>
    </ul>
  </div>
</div>

rakusuke/app/views/schedules/new.html.erb
<div data-role="header">
  <%= link_to '戻る', schedules_path, "data-icon"=>"arrow-l" %>
  <h1>スケジュール登録</h1>
</div>

<%= render 'form' %>

rakusuke/app/views/schedules/show.html.erb
<div data-role="header">
  <%= link_to '戻る', schedules_path, "data-icon"=>"arrow-l" %> |
  <%= link_to '編集', edit_schedule_path(@schedule), "data-icon"=>"arrow-l" %>
  <h1>スケジュール詳細</h1>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>予定日:</strong>
  <%= @schedule.date %>
</p>

<p>
  <strong>送迎区分:</strong>
  <%= @schedule.pickup_name %>
</p>

<p>
  <strong>送迎先:</strong>
  <%= @schedule.transfer_destination.name unless @schedule.transfer_destination.blank? %>
</p>

<p>
  <strong>到着予定時刻:</strong>
  <%= @schedule.estimated_time_of_arrival_ %>
</p>

<p>
  <strong>氏名:</strong>
  <%= @schedule.child.full_name unless @schedule.child.blank? %>
</p>

<p>
  <strong>利用時間帯:</strong>
  <%= @schedule.use_time_name %>
</p>

<p>
  <strong>下校時刻:</strong>
  <%= @schedule.get_out_of_school_time_ %>
</p>

<p>
  <strong>希望時刻:</strong>
  <%= @schedule.desired_time_ %>
</p>

<p>
  <strong>ステータス:</strong>
  <%= @schedule.status_name %>
</p>

<p>
  <strong>備考:</strong>
  <%= @schedule.memo %>
</p>