rakusuke/config/routes.rb
Rails.application.routes.draw do

  devise_for :people, only: [:sign_in, :sign_out, :session, :password]
  resources :people
  devise_for :admins

  resources :transfer_destinations

  resources :children

  resources :schedules do
    member do
      patch 'edit_transfer_dests'
    end
  end

  post 'schedules/kakutei/:ids' => 'schedules#kakutei'

  root :to => 'home#index'

end

rakusuke/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rakusuke</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <script>
    $(function() {
      $("#datepicker").datepicker();
      $('#datepicker').datepicker("option", "dateFormat", 'yy/mm/dd');
    });
  </script>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div data-role="header">


    <% if current_person.is_a?(Admin) %>
      <strong><%= current_person.email %></strong>.
      <%= link_to 'パスワード変更', edit_admin_registration_path, :class => 'navbar-link' %> |
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %> |
    <% elsif current_person.is_a?(Person) %>
      <strong><%= current_person.email %></strong>.
      <%= link_to "ログアウト", destroy_person_session_path, method: :delete, :class => 'navbar-link'  %> |
    <% else %>
    <%#
             <%= link_to "管理者登録（暫定）", new_admin_registration_path, :class => 'navbar-link'  %>

    <% end %>
      <%= link_to "ホーム", root_path, :class => 'navbar-link'  %>
  <%= yield %>
    </div>

</body>
</html>

rakusuke/app/views/layouts/application_smart_phone_iphone.html.erb
<html>
<head>
  <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>iPhone</title>
  <%= stylesheet_link_tag "mobile_application" %>
  <%= javascript_include_tag "mobile_application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div data-role="page">
  <p class="navbar-text pull-right">

    <% if current_person.is_a?(Admin) %>
      <strong><%= current_person.email %></strong>.
      <%= link_to 'パスワード変更', edit_admin_registration_path, :class => 'navbar-link' %> |
      <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %> |
    <% elsif current_person.is_a?(Person) %>
      <strong><%= current_person.email %></strong>.
      <%= link_to "ログアウト", destroy_person_session_path, method: :delete, :class => 'navbar-link'  %> |
    <% end %>
    <%= link_to "ホーム", root_path, :class => 'navbar-link'  %>

    <%= yield %>
  </div>
</body>
</html>