rakusuke/config/routes.rb
Rails.application.routes.draw do

  devise_for :people, only: [:sign_in, :sign_out, :session, :password]
  resources :people
  devise_for :admins

  resources :transfer_destinations

  resources :children

  resources :schedules do
    member do
      patch 'edit_transfer_dests'
    end
  end

  post 'schedules/kakutei/:ids' => 'schedules#kakutei'

  root :to => 'home#index'

end

rakusuke/app/models/person.rb
class Person < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :children, :dependent => :destroy
  has_many :schedules, :dependent => :destroy

  before_create :set_type

  def set_type
    self.type = self.class
  end


end

rakusuke/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.where("type = ?", "Person")
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: '登録されました。' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if person_params[:password].blank? && person_params[:password_confirmation].blank?
        if @person.update_without_password(person_params)
          format.html { redirect_to @person, notice: '更新されました。' }
          format.json { render :show, status: :ok, location: @person }
        end
      elsif @person.update(person_params)
        format.html { redirect_to @person, notice: '更新されました。' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: '削除されました。' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :address, :email, :email_flg, :type, :memo, :deleted_at, :password, :password_confirmation)
    end
end

rakusuke/app/helpers/people_helper.rb
module PeopleHelper
end

rakusuke/app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :姓 %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :名 %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :住所 %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :パスワード %><br />
    <%= f.password_field :password, autofocus: true, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :パスワード確認 %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :お知らせメール送信可否 %><br>
    <%= f.check_box :email_flg %>
  </div>
  <div class="field">
    <%= f.label :メモ %><br>
    <%= f.text_area :memo %>
  </div>
  <!--<div class="field">-->
    <!--<%= f.label :deleted_at %><br>-->
    <!--<%= f.datetime_select :deleted_at %>-->
  <!--</div>-->
  <div class="actions">
    <%= f.submit '送信' %>
  </div>
<% end %>

rakusuke/app/views/people/edit.html.erb
<div data-role="header">
  <%= link_to '戻る', people_path, "data-icon"=>"arrow-l" %> |
  <%= link_to '詳細', @person, "data-icon"=>"arrow-R" %>
  <h1>保護者編集</h1>
</div>

<%= render 'form' %>

rakusuke/app/views/people/index.html.erb
<h1>保護者</h1>


<%= link_to '新規作成', new_person_path %>

<table class="tablesorter">
  <thead>
    <tr>
      <th>姓</th>
      <th>名</th>
      <th>住所</th>
      <th>Email</th>
      <th>お知らせメール可否</th>
      <th>メモ</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.last_name %></td>
        <td><%= person.first_name %></td>
        <td><%= person.address %></td>
        <td><%= person.email %></td>
        <td><%= person.email_flg %></td>
        <td><%= person.memo %></td>
        <td><%= link_to '詳細', person %></td>
        <td><%= link_to '編集', edit_person_path(person) %></td>
        <td><%= link_to '削除', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

rakusuke/app/views/people/new.html.erb
<div data-role="header">
  <%= link_to '戻る', people_path, "data-icon"=>"arrow-l" %> |
  <h1>保護者登録</h1>
</div>

<%= render 'form' %>

rakusuke/app/views/people/show.html.erb
<script src="http://code.jquery.com/jquery-1.8.3.js"></script>
<script src="http://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>

<div data-role="header">
  <%= link_to '戻る', people_path, "data-icon"=>"arrow-l" %> |
  <%= link_to '編集', edit_person_path(@person), "data-icon"=>"arrow-l" %>
  <h1>保護者詳細</h1>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong>姓:</strong>
  <%= @person.last_name %>
</p>
<p>
  <strong>名:</strong>
  <%= @person.first_name %>
</p>
<p>
  <strong>住所:</strong>
  <%= @person.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<p>
  <strong>お知らせメール可否:</strong>
  <%= @person.email_flg %>
</p>

<p>
  <strong>メモ:</strong>
  <%= @person.memo %>
</p>



<div id="show_area"></div>
<%= link_to '新規作成', new_child_path(:person_id => @person.id) %>


<script type = "text/javascript">

    $(document).ready(function(){
$.get("<%= children_path :person_id => @person.id %>",
function(data) { $('#show_area').html(data) } )

$('a.index').click(function() {
$.get("<%= children_path :person_id => @person.id %>",
function(data) { $('#show_area').html(data) } )
})

})
</script>